### ISSUE TITLE
Delete Installation is impossible

### ISSUE THREAD

**Issue by JuLink** [netreconlab/Parse-Swift#11]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

I don't have the ability to change the Parse Server version but I use the latest version of Parse Swift

### Issue Description
If a ParseInstallation is deleted on the server side, it's impossible to recover from it. It's not possible to create/delete/fetch/replace/save on ParseInstallation.current. Everything ends up in an error, either the object is not found or it's not allowed.

The SDK doesn't seems to allow the cleaning of the ParseInstallation.current to create a new one. Even deleting and installing the app again does not clear the ParseInstallation.current.
The setter of ParseInstallation.current is internal so can't be use.
I did not found any public API to delete ParseStorage and or KeychainStore because they are both non-public struct.

### Steps to reproduce

- Initialise the ParseSwift sdk
- Set the deviceToken property
- save the object to sync it with the server
- On the server dashboard delete the Installation
- try to use the ParseInstallation.current and save it (or create, replace, delete, fetch)

### Actual Outcome

Every operation on the ParseInstallation.current fails

### Expected Outcome

Being able to reset the local ParseInstallation somehow to recover.

### Environment

Client
- Parse Swift SDK version: `4.14.2`
- Xcode version: `14.0.1`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `any version but I'm using 15.5 or 16.1`

Server
- Parse Server version: `2.8.2`
- Operating system: `do not know`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `do not know`

Database
- System (MongoDB or Postgres): `do not know`
- Database version: `do not know`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `do not know`

### Logs

Doing the save/replace/fetch operation leads to:
```
{
  "code": 101,
  "error": "Object not found for update."
}
```

Doing a delete operation leads to:
```
{
  "code": 119,
  "error": "Clients aren't allowed to perform the delete operation on the installation collection."
}
```

Doing the create operation leads to:
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /parse/installations/Fhg7BEMBsW</pre>
</body>
</html>
```

**Comment by cbaker6** [comment]
You can delete the installation on the client by:

1. [Logging out](https://netreconlab.github.io/Parse-Swift/release/documentation/parseswift/parseuser/logout(options:)-5l3vm) the user, example code 
2. Setting `deletingKeychainIfNeeded = true` when [configuring the SDK](https://netreconlab.github.io/Parse-Swift/release/documentation/parseswift/configuration) and deleting the app as you described

**Comment by JuLink** [comment]
I do not use the login feature of the SDK, my only use is the ParseInstallation part.

The login is managed somewhere else and I simply retrieve an account ID from the login part, then I set a custom property on the ParseInstallation to allow my backend to send Push Notification for the user corresponding to that ID and with de deviceToken from the Installation.

My goal if possible would be to retrieve the ParseInstallation.current, try to fetch the updated version if it exist (it can be deleted not from the application itself), if it does not, create a new installation and sync it. But I can't figure it out 🤔

**Comment by cbaker6** [comment]
Even if you don’t use Parse for login, when you detect the app throwing errors like you’ve shown, use the `try? await User.logout()` method to delete the installation and a new one will automatically be created locally for you to save. For example:

```swift
do {
    try? await User.logout() // You can ignore any errors thrown from logging out
    guard let newInstallation = Installation.current else {
        throw Error("Missing new installation") // You should throw some custom error here
    }
    // Can now use/save new installation
    print(newInstallation)
}
```

**Comment by cbaker6** [comment]
Closing as https://github.com/netreconlab/Parse-Swift/issues/11#issuecomment-1304312552 should solve the problem you are having.
