### ISSUE TITLE
Adding a relationship to a mergeable object

### ISSUE THREAD

**Issue by bcbeta** [netreconlab/Parse-Swift#125]
### New Issue Checklist

- [X ] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [ X] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases).  using server 4.5 (back4app)

### Issue Description
When adding new relationship objects to an existing mergeable object, "Object not found" error is thrown.

### Steps to reproduce

 ```
var photos = [PFPhoto]()
for photoURL in photoURLs{
        var pfPhoto = PFPhoto()
        pfPhoto.thumbnailURL = photoURL
        pfPhoto.fullURL = photoURL
        photos.append(pfPhoto)
      }
      if photos.count > 0 {
               var updatedObservation = existingObservation.mergeable
               updatedObservation.observationPhotos = photos
                 _ = try await updatedObservation.save()
                  }
           }
      }
        catch {
             print(error)
           }

```
### Actual Outcome
Save the pfPhoto and observation objects.

### Expected Outcome
Throws "object not found" error

### Environment

Client
- Parse Swift SDK version: `5.8`
- Xcode version: `14.3.1`
- Operating system (iOS, macOS, watchOS, etc.): `iOS 16.4`

Server
- Parse Server version: `4.5`

**Comment by cbaker6** [comment]
Are you able to take a shot at a pull request with a fix and test case? If so, I’ll review it

**Comment by bcbeta** [comment]
Unfortunately I don't have the knowledge/skill to do this. Maybe someone else will encounter this issue and come up with a fix.

**Comment by cbaker6** [comment]
Looking at this further, I believe the issue is you are trying to update relationships to objects that haven't been saved yet. Is your problem fixed if you `photos.saveAll()` first and then update the relationships?

**Comment by cbaker6** [comment]
Feel free to reopen if my solution above doesn’t work.
