### ISSUE TITLE
fields named "id" are skipped in nested objects

### ISSUE THREAD

**Issue by wtholliday** [netreconlab/Parse-Swift#140]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description
Fields named "id" are skipped in nested objects.

### Steps to reproduce

```swift
    struct MyType: Hashable, Codable {
        // BUG: if we call this "id" then parse won't save it
        var id: String
    }

    struct MyParseObject: ParseObject {
        public var originalData: Data?
        public var objectId: String?
        public var createdAt: Date?
        public var updatedAt: Date?
        public var ACL: ParseSwift.ParseACL?

        var nested: MyType?
        public init() {}
    }

    func test_parseEncodeDictionary() throws {
        var myObject = MyParseObject()
        myObject.nested = MyType(id: "test1")

        let object = try ParseCoding.parseEncoder()
            .encode(myObject,
                    acl: nil,
                    collectChildren: true,
                    objectsSavedBeforeThisOne: nil,
                    filesSavedBeforeThisOne: nil)
        XCTExpectFailure("currently skipping id fields")
        XCTAssertEqual(String(decoding: object.encoded, as: UTF8.self), #"{"nested":{"id":"test1"}}"#)
    }
```

### Actual Outcome
Fields named "id" are ignored and don't make it to the server.

### Expected Outcome
Fields named "id" (not in ParseObjects) should still be saved or an error should be reported so the user knows to rename the field.

### Environment

Client
- Parse Swift SDK version: `5.8.2`
- Xcode version: `15.1 (15C65)`
- Operating system (iOS, macOS, watchOS, etc.): `macOS`
- Operating system version: `14.2.1 (23C71)`

Server
- Parse Server version: `4.5.0`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `BackForApp`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `BackForApp`

**Comment by cbaker6** [comment]
`id` is an internal keyword for all Parse classes and should not be used to name a property or else you will get unexpected behavior. This is not just for ParseSwift, but all of the SDKs. You can use a name like `localId`, key names you are not suppose to use are: https://github.com/netreconlab/Parse-Swift/blob/c0a3a452a20d9f3ab9cb2a2ea790d0359a3beca0/Sources/ParseSwift/Coding/ParseEncoder.swift#L75-L82

**Comment by wtholliday** [comment]
Why skip fields inside a struct which isn't a ParseObject? Seems like it could store them without any issues, since they are just represented as json strings on the server, right?

**Comment by cbaker6** [comment]
If you think you have a better solution, feel free to open a PR with your suggestion.

**Comment by cbaker6** [comment]
Reopening this, will see if I can provide a fix by the end of the week

**Comment by roaring-b** [comment]
Thanks, Corey! Discovering this the hard way was a huge pain.

**Comment by cbaker6** [comment]
I looked further into this and attempting to provide a fix now will cause more harm than good. The `ParseEncoder` is tricky as there are a number of properties that shouldn't be sent to the server.

As a workaround, you can do any of the following:
1. Not use property names that contain any of the keys being skipped by the SDK, https://github.com/netreconlab/Parse-Swift/issues/140#issuecomment-1872593121
2. Encode your respective object that contains the keys being skipped to JSON string before storing it in your `ParseObject` (the string will be stored as-is and won't skip keys). You can then decode your JSON string whenever you fetch your object from the server. You could then add another property with a getter and setter that decodes the string in the getter and encodes the string on the setter similar to

**Comment by cbaker6** [comment]
See #177 for fix
