### ISSUE TITLE
Sending an object to a ParseCloudable function strips the data 

### ISSUE THREAD

**Issue by jaysonng** [netreconlab/Parse-Swift#153]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description

Sending a full object to a ParseCloudable function strips the data out by converting the object to a Pointer as its parameter.

### Steps to reproduce

Create a test function either in JS CloudCode or Swift CloudCode (Parse-Swift-Server) and call that function while sending out a full ParseObject as a parameter.

The cloudcode function parameter will only receive a Pointer object with only the objectId as its data.

### Actual Outcome

ParseObject I send as a full object becomes a Pointer object.

### Expected Outcome

ParseObject should stay as a full ParseObject so I can access the data as needed.

### Environment

Client
- Parse Swift SDK version: `5.8.2`
- Xcode version: `15.2`
- Operating system (iOS, macOS, watchOS, etc.): `macOS`
- Operating system version: `14.1.1`

Server
- Parse Server version: `6.4`
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongodb`
- Database version: `6.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### Logs

Sample parameter received with objectId:
```
{\"params\":{\"role\":{\"__type\":\"Pointer\",\"className\":\"_Role\",\"objectId\":\"BDC5nSB8eQ\"}}
```
and without objectId
```
{\"role\":{\"ACL\":{\"role:superAdmin\":{\"read\":true,\"write\":true}},\"createdAt\":\"2023-11-29T07:25:24.276Z\",\"name\":\"beta\",\"updatedAt\":\"2024-02-17T03:38:38.990Z\"}}
```

**Comment by cbaker6** [comment]
This is suppose to happen. This is how the other SDKs work and how the server expects the data. Unless you find examples on the server-side or other SDKs that support what you are trying to do, no changes will be made here.

in cloud code, you can easily fetch objects from pointers.

**Comment by jaysonng** [comment]
> This is suppose to happen. This is how the other SDKs work and how the server expects the data. Unless you find examples on the server-side or other SDKs that support what you are trying to do, no changes will be made here.
> 
> in cloud code, you can easily fetch objects from pointers.

gotcha. 

Basically before I tried the beforeSave route, I was sending the object I wanted to edit over to cloudcode and do my checks there and tried to save it in cloudcode. 

but beforeSave should work and do my checks there once we figure out whats wrong with the pointer. 

thanks,
