### ISSUE TITLE
Make ParseObject Sendable

### ISSUE THREAD

**Issue by Dan1973KS** [netreconlab/Parse-Swift#155]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation

Since Xcode 15 with Build Setting Strict Concurrency Checking set to Targeted, the compiler warns that ParseObject is not conform to Sendable. So it cannot leave its actor boundaries.
Trying to make ParseObject conform to Sendable fails because it contains the ParseACL type which is not conform as well.

### Feature / Enhancement Description
 Please make ParseObject also conform to Sendable.
### Alternatives / Workarounds
 Ignoring the warnings. At some case it is possible to annotate import ParseSwift with @preconcurrency.

**Comment by cbaker6** [comment]
See https://github.com/netreconlab/Parse-Swift/discussions/119#discussioncomment-6191852

**Comment by Dan1973KS** [comment]
> See https://github.com/netreconlab/Parse-Swift/discussions/119#discussioncomment-6191852

Thanks. 
And sorry for re-issueing...

**Comment by cbaker6** [comment]
As of version https://github.com/netreconlab/Parse-Swift/releases/tag/6.0.0, the SDK is now under complete concurrency. Please see https://github.com/netreconlab/Parse-Swift/discussions/225 for more details.
