### ISSUE TITLE
[feature request] To add includeKeys to ParseUser.login

### ISSUE THREAD

**Issue by michaelnew** [netreconlab/Parse-Swift#16]
### New Feature / Enhancement Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x ] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation
Currently there's no way (that I can find at least) of asking for a key to be included when doing `ParseUser.login`. For example, if the user object has a pointer to, say, the `UserPreferences` table, it would be nice to be able to load that during login without having to make a second request.

### Feature / Enhancement Description
Would be cool if `ParseUser.login` worked like `ParseUser.fetch`, with a function signature something like this:
```swift
public static func login(
    username: String,
    password: String, 
    includeKeys: [String]? = nil,
    options: API.Options = [], 
    callbackQueue: DispatchQueue = .main,
    completion: @escaping (Result<Self, ParseError>) -> Void
)
```

### Example Use Case
1. Call `myUser.login( "smartattractiveguy", "verygoodpassword", includeKeys: ["appPreferences])`
2. *Don't* bother calling `myUser.appPreferences.fetch()`, because it's already been loaded.
3. ...
4. Profit

**Comment by cbaker6** [comment]
The limitation is on the Parse Server, not the Swift SDK, you can read more about why the server doesn’t have it: https://community.parseplatform.org/t/fetch-with-login/1233

**Comment by cbaker6** [comment]
Closing as this is a limitation of the Parse Server REST API. I recommend coming on the Parse Community thread or opening an issue on the parse-server.

**Comment by michaelnew** [comment]
Thanks, after opening the issue it occurred to me that might be the case, so sorry for the noise. And it looks like there have been a few open issues and PRs that have gone nowhere over the years, so I maybe it's just not meant to be.

Appreciate the feedback.
