### ISSUE TITLE
Error while query users with emails that contains +(plus) character

### ISSUE THREAD

**Issue by Drendroyt** [netreconlab/Parse-Swift#189]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

When I try to query object from my database (based on back4app) with email that contains +(plus) characters I got Parse Error "Object not found".
If I try to query objects with email that contains other special characters- "_" or "." everything working ok. 

### Steps to reproduce

- create _User object with email that contains +(plus) character. For example "kiril+1@gmail.com"
- fetch parse object from swift code (example with login below )
```swift
    func login(user: ParseUserObject) async throws {
        guard let email = user.email?.lowercased(), let password = user.password else {
            throw ParseError.Code.unknownError
        }
        // Fetch username from Parse(user provide only email/pass for login)
        var constraints = [QueryConstraint]()
        constraints.append(equalTo(key: "email", value: email))
        let query = ParseUserObject.query(constraints)
        let parseUser = try await query.first()
        // or you can use
        // let query = ParseUserObject.query("email" == email.lowercased())
        guard let username = parseUser.username else {
            throw ParseError.Code.unknownError
        }
        try await ParseUserObject.login(username: username, password: password)
        setIsAuthorized(true)
    }
```

### Actual Outcome

try await query.first() throw an Parse Error (object not found)

### Expected Outcome

Existing object 

### Environment

Xcode, iOS simulator (or physical iPhone), parse database based on back4app service  

Client
- Parse Swift SDK version: `5.11.3`
- Xcode version: `15.4`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `18.0`

Server
- Parse Server version: `3.10.0`
- Operating system: `Linux(maybe)`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `back4app server`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `back4app server`

### Logs

▿ ParseError code=101 error=Object not found on the server.
  - code : ParseSwift.ParseError.Code.objectNotFound
  - message : "Object not found on the server."
  - otherCode : nil
  - error : nil

**Comment by cbaker6** [comment]
Parse Server [3.10.0](https://github.com/parse-community/parse-server/releases/tag/3.10.0) is extremely old and pre-dates Parse-Swift by +1 year, so many issues and security patches have been addressed in the latest version, [7.4.0](https://github.com/parse-community/parse-server/releases/tag/7.4.0). Also, if you plan to use LiveQuery with ParseSwift, the lowest version of the server that will work correctly is `4.0.0`. See https://github.com/netreconlab/Parse-Swift/discussions/72 for details.

The issue you mentioned above should be fixed in #191
