### ISSUE TITLE
Allow main app to share local data and keychain with it's app extensions

### ISSUE THREAD

**Issue by Aziz-AnyDesk** [netreconlab/Parse-Swift#26]
### ParseSwift doest not allow sharing local data with it's extensions
Parse-IOS Objective-C SDK allows main iOS app to share local data like PFUser.current, PFInstallation.current and e.t.c with its app extensions like share extension, broadcasting extension and e.t.c.. Please add support for this feature for ParseSwift.

### Feature / Enhancement Description
When this feature enabled, ParseUser.current and ParseInstallation.current should return the same value from the main app if it is called inside app extension. The main app should share keychain with its' extensions.

### Example Use Case
Main app logs in user and launches broadcasting extension. Broadcasting extension calls ParseUser.current and gets the same user logged in in the main app. Broadcast extension is aware of the current user from the main app and shares keychain.

**Comment by cbaker6** [comment]
This was already added in https://github.com/parse-community/Parse-Swift/pull/378. In the Swift SDK, all `.current` items are securely stored in the Keychain, so you will need to properly [enable keychain sharing via access groups](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps) as well as add the correct `Signing & Capabilities`. Be sure to look through the differences between `App Groups` and `Keychain Access Groups` and how to use them together in the posted link.

The way these are stored in the Swift SDK is a lot different than the Objective-C SDK and the Swift SDK doesn't have issues like: https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1648 or https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1220

**Comment by Aziz-AnyDesk** [comment]
Thank you. Really appreciate your reply.
