### ISSUE TITLE
include not working for LiveQuery

### ISSUE THREAD

**Issue by vdkdamian** [netreconlab/Parse-Swift#38]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description
`include()` and `includeAll()` are not working on LiveQueries.

### Steps to reproduce
Set an include on a LiveQuery

### Actual Outcome
I am seeing the reference pointer in the result

### Expected Outcome
The attached pointer in the result.

### Environment

Client
- Parse Swift SDK version: `4.16.2`
- Xcode version: `14.2`
- Operating system (iOS, macOS, watchOS, etc.): `iOS, macOS`
- Operating system version: `iOS 16.2, macOS 13.1`

Server
- Parse Server version: `5.2.3`
- Operating system: `Back4App`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

**Comment by cbaker6** [comment]
According to the [LiveQuery spec](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification), `include` isn't supported. I recommend you ask your question on the parse-server repo. If it turns out `include` is supported on the server already, post the links to the server code and the feature will be added to the SDK. If not, you will have to ask the parse-server team to add the feature.

**Comment by cbaker6** [comment]
Closing this due to older discussions about the limitations on the server-side here: https://github.com/parse-community/parse-server/issues/1686

**Comment by cbaker6** [comment]
Looks like you can use CloudCode, see here: https://community.parseplatform.org/t/parse-live-query-include/3175/3?u=cbaker6

**Comment by vdkdamian** [comment]
Thanks! I'll try this out. Will help me a lot!
