### ISSUE TITLE
Unable to use PreviewProviders using a ParseObject

### ISSUE THREAD

**Issue by vdkdamian** [netreconlab/Parse-Swift#54]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description
I am unable to use PreviewProviders if i require a ParseObject to be passed as parameter.

### Steps to reproduce
Create a variable of a new ParseObject and set custom data for it.
I have set all default variables like `objectId`, `createdAt`, `updatedAt`. And also some cutom variables.

Here is an example:

```
public struct Product: ParseObject {
    public var objectId: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var ACL: ParseACL?
    public var originalData: Data?
    
    public var user: Pointer<User>?
    public var amount: Int?
    
    public init() {
        
    }
}
```

```
var newProduct = Product()
        
newProduct.objectId = UUID().uuidString
newProduct.createdAt = Date()
newProduct.updatedAt = Date()
        
newProduct.user = try? User.current?.toPointer()
newProduct.amount = (1...5).randomElement()

struct CartDetail_Previews: PreviewProvider {
    
    static var previews: some View {
        CartDetail(product: newProduct)
    }
}
```

### Actual Outcome
An error 
<img width="469" alt="Scherm­afbeelding 2023-01-29 om 11 15 42" src="https://user-images.githubusercontent.com/44820440/215320022-98987584-bd53-4595-8d67-0b1d6118e824.png">

### Environment

Client
- Parse Swift SDK version: `4.16.2`
- Xcode version: `14.2`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`, `macOS`
- Operating system version: `16.2`, `13.1`

Server
- Parse Server version: `5.2.3`
- Operating system: `Back4App`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB `
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

**Comment by cbaker6** [comment]
This seems like a design issue in your code, you are using a “model” which is a ParseObject directly in your view and not handling it properly. Product should also be created/initialized inside the struct. You can write static functions to do that if you need to. I use Parse-Swift, previews, and MVVM in the example app I open-sourced a couple of years ago, you can look there for guidance https://github.com/netreconlab/SnapCat/blob/3098fcbe474a8e623c227d58f4883df9de334718/SnapCat/Profile/ProfileUserDetailsView.swift#L165

**Comment by cbaker6** [comment]
From the error in your screenshot, it says ParseStorage.swift line 51 can’t be unwrapped, you should find that line in your ParseSwift version, it’s most likely you don’t have the SDK initialized properly. 

This is happening because you are using “User.current” in your preview which requires the Keychain and requires the SDK to be initialized. If you create a dummy User, your issue will probably go away as you won’t need to init the SDK anymore. You should always create dummy objects to populate your previews.

**Comment by vdkdamian** [comment]
> This is happening because you are using “User.current” in your preview which requires the Keychain and requires the SDK to be initialized. If you create a dummy User, your issue will probably go away as you won’t need to init the SDK anymore. You should always create dummy objects to populate your previews.

Omg yes, of course... stupid from me. Sorry for the question, thanks for the help tho!
