### ISSUE TITLE
User.become with a sessionToken fails

### ISSUE THREAD

**Issue by softcleandev** [netreconlab/Parse-Swift#78]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description

I've just upgraded from Parse-Swift (4.14.2) to Parse-Swift (OG) 5.2.1 via pod.
After the required changes in my app, it's no longer possible to login as user via the following function

```
User.become(sessionToken: String,
                              options: API.Options = [],
                              callbackQueue: DispatchQueue = .main,
                              completion: @escaping (Result<Self, ParseError>) -> Void)
```

`User.login()` with credentials works fine.

### Steps to reproduce

- Upgrade from 4.14.2 to 5.2.1 . [See migration guide](https://github.com/netreconlab/Parse-Swift/discussions/74)
- Try to login via User.become(sessionToken, ...)

### Actual Outcome

I always get this error:
`ParseError code=101 error=Object not found.`

The user exists and the sessionToken is also valid.

Here is my User struct:
```
 struct User: ParseUser {
     //: These are required by `ParseObject`.
     var objectId: String?
     var createdAt: Date?
     var updatedAt: Date?
     var ACL: ParseACL?
     var originalData: Data?

     //: These are required by `ParseUser`.
     var username: String?
     var email: String?
     var emailVerified: Bool?
     var password: String?
     var authData: [String: [String: String]?]?

     //: Custom properties
     var uniqueSession: Bool?
     var comment: String?
 }
```

### Expected Outcome

Normally the login should run without any problems. It also worked with the older version 4.14.2 from [ParseSwift (parse-community)](https://github.com/parse-community/Parse-Swift/)

### Environment

Client
- Parse Swift SDK version: `5.2.1`
- Xcode version: `14.2`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `16.3.1`

Server
- Parse Server version: `6.0.0`
- Operating system: `Ubuntu Server 22.0.4 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `self hosted`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.1.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `self hosted`

### Logs

The only log I can find on the server:
```
2023-03-15T10:05:31.253Z - Object not found.
2023-03-15T10:05:31.234Z - REQUEST for [GET] /parse/classes/_User/me: {}
```

**Comment by cbaker6** [comment]
Thanks for reporting. `become()` should work in the linked PR which will be merged to the main soon.

**Comment by cbaker6** [comment]
How hard/easy was it to migrate your app via #74? Are you able to comment in that discussion so others can understand the amount of work they have to do?

**Comment by softcleandev** [comment]
> 

@cbaker6 I have switched to OG version in ca. 30 minutes. I had to change some functions to await/async "logic". but all in all it was very easy.
thx for fast reply.
