### ISSUE TITLE
Could not build Objective-C module 'Parse'

### ISSUE THREAD

**Issue by spiderguy84** [netreconlab/Parse-Swift#91]
I added pod 'ParseLiveQuery' to my pod file, but when I tried to build in my app running mostly all Obj-C, I got the error message ParseLiveQuery/Client.swift:11:8 Could not build Objective-C module 'Parse'

**Comment by cbaker6** [comment]
This repo only works with Swift and has nothing to do with [ParseLiveQuery for objective-c](https://github.com/parse-community/ParseLiveQuery-iOS-OSX). You should only open issues here related to ParseSwift<sup>OG</sup>
