### ISSUE TITLE
Getting "Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value" error

### ISSUE THREAD

**Issue by jaysonng** [netreconlab/Parse-Swift#94]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/netreconlab/Parse-Swift/releases). 

### Issue Description

"Thread 4: Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value"

when running query with .includeAll() on my @main app file.

The error specifically comes from the firstCommand() function in Query.swift

![Screenshot 2023-05-01 at 3 47 45 PM](https://user-images.githubusercontent.com/440445/235429255-e4997b18-10a0-4368-9aee-ada516106177.png)

### Steps to reproduce

Call some query on the same view where you run  ParseSwift.initialize() 

In my case, ParseSwift.initilize is called within init() in a Task { }
![Screenshot 2023-05-01 at 4 51 01 PM](https://user-images.githubusercontent.com/440445/235431256-bc44e43f-7d82-43a3-8c81-38f7e22a52b5.png)

I receive this warning in the console for the few times that it does not crash

`nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for xxxxxxxxx:443`

### Actual Outcome

A lot of the times it crashes with the said error. only some of the time does it work as expected.

### Expected Outcome

There should be no crash and the query should be called after initialization of Parse.

### Environment

Client
- Parse Swift SDK version: `5.4.1`
- Xcode version: `14.3`
- Operating system (iOS, macOS, watchOS, etc.): `iPad OS, iOS, MacOS simulator`
- Operating system version: `16.4.1`

Server
- Parse Server version: `5.2.4`
- Operating system: ``
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: ``
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local Heroku`

**Comment by cbaker6** [comment]
> Call some query on the same view where you run ParseSwift.initialize()

You are calling your initializer way too late if you are calling it in a view. In addition, placing the Swift SDK init in a view may cause it to be called multiple times, which can lead to a ton of other issues.

The Swift SDK should be called once, and it should be called early when the app opens, which is why it has historically been in the `AppDelegate`.

I can try to submit a partial fix, but your current design will continue to lead to issues as views can be regenerated, causing the SDK to be reinitialized.

**Comment by jaysonng** [comment]
I see. I just moved it to the @main view. 

I guess ill copy how you have it setup on carekit with the appdelegate. :) thanks again

**Comment by cbaker6** [comment]
The linked PR and version should fix the direct issue you are facing.

> I guess ill copy how you have it setup on carekit with the appdelegate.

If you are looking through the CareKit example, this branch is cleaner and will be merged in the near future: https://github.com/netreconlab/CareKitSample-ParseCareKit/tree/newCareKit

You will want to setup your `AppDelegate` in a similar way:
- Make sure AppDelegate is wrapped with `@UIApplicationDelegateAdaptor(AppDelegate.self)`. You can pass it through the environment if you intend to use `AppDelegate` in other places of your app: https://github.com/netreconlab/CareKitSample-ParseCareKit/blob/f5965788f28eee84a4eab382ab785e3badd6a1c6/OCKSample/OCKSampleApp.swift#L15-L22
- Make your `AppDelegate` class conform to `ObservableObject` and use `@Published` for any properties you want to update your views https://github.com/netreconlab/CareKitSample-ParseCareKit/blob/f5965788f28eee84a4eab382ab785e3badd6a1c6/OCKSample/AppDelegate.swift#L39-L42
- Then you can place the ParseSwift init in didFinishLaunching like you use to do in UIKit lifecycle apps: https://github.com/netreconlab/CareKitSample-ParseCareKit/blob/b362e420952d2c50038dd7871711b532b18e83ac/OCKSample/Extensions/AppDelegate%2BUIApplicationDelegate.swift#L13-L27
  - Note that `PCKUtility.configureParse()` calls ParseSwift init, so if you are interested in using a `.plist` file to configure ParseSwift, see: https://github.com/netreconlab/ParseCareKit/blob/566f68ef230e4285eb9e19a3d1045947d5a74eef/Sources/ParseCareKit/PCKUtility.swift#L18-L94
